### ISSUE TITLE
Cannot start embedded server: WFLYEMB0022: Cannot invoke 'start' on embedded process: WFLYSRV0141: Cannot start server: JBTHR00005: Operation failed: Failed to start service: COM00008: Parameter 'abstractPath' must not be empty

### ISSUE THREAD

**Issue by PhalgunNKrishna** [mieckert/keycloak-heroku#5] opened 2021-07-05 01:19 UTC
Hello mieckert,

I have an almost identical error message as @margaretupshur discussed in her issue ( https://github.com/mieckert/keycloak-heroku/issues/4). I commented on that issue but I'm not sure if you've seen it so I am creating a new one here.

I deployed this Keycloak instance to Heroku to work in tandem with my web application about 3 months ago but first noticed this error message in my Heroku logs on June 1,. Also, I noticed your comment on @margaretupshur's issue regarding the line: `Keycloak 12.0.0 (WildFly Core 13.0.3.Final)`. I am having a similar error message whereas mine says `Keycloak 12.0.4 (WildFly Core 13.0.3.Final)` instead.

**Comment by mieckert** [comment] 2021-08-03 12:12
Duplicate of #4

**Closed as completed by mieckert** 2021-08-03 12:12 UTC
